<a href="https://colab.research.google.com/github/DanYT2/machine_learning/blob/main/Perceptron%20and%20LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

targets = np.array([0, 1, 1, 0])

In [ ]:
class Perceptron:
  def __init__(self, num_inputs, lr = 0.1):
    self.weights = np.zeros(num_inputs)
    self.bias = 0
    self.lr = lr

  def predict(self, inputs):
    weighted_sum = np.dot(inputs, self.weights) + self.bias
    output = 1 if weighted_sum > 0 else 0
    return output


In [ ]:
# Create neuron (perceptron)

clf = Perceptron(num_inputs=2, lr=0.1)

for i in range(100):
  for input_data, target in zip(inputs, targets):
    prediction = clf.predict(input_data)
    error = target - prediction

    clf.weights += clf.lr * error * input_data
    clf.bias += clf.lr + error

In [ ]:
# Testing
print('Input\t\tOutput')
for input_data in inputs:
  prediction = clf.predict(input_data)
  print(f"{input_data}\t\t{prediction}")

Input		Output
[0 0]		1
[0 1]		1
[1 0]		0
[1 1]		0


In [ ]:
# Reshape inputs for LSTM

inputs = np.reshape(inputs, (inputs.shape[0], inputs.shape[1], 1))

In [ ]:
from keras.layers.serialization import activation
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(units=4, input_shape=(2,1)),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(inputs, targets, epochs=500, verbose=0)

predictions = model.predict(inputs)
predictions = np.round(predictions).flatten()

print('Input\t\tOutput')
for input_data, prediction in zip(inputs, predictions):
  print(f"{input_data}\t\t{prediction}")

1/1 [==============================] - 1s 895ms/step
Input		Output
[[0]
 [0]]		0.0
[[0]
 [1]]		1.0
[[1]
 [0]]		1.0
[[1]
 [1]]		0.0
